apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: gcr.io/qwiklabs-gcp-04-80ef7a340d3b/sample-app:v1.0
        ports:
        - containerPort: 8080
